### ISSUE TITLE
fix: discord times out when openai takes too long

### ISSUE THREAD

**Issue by 0xSage** [0xSage/gnosisgpt#15]
Ask a complicated question, model lags, get error:

```sh
2023-04-20 11:36:33 WARNING  discord.gateway Shard ID None heartbeat blocked for more than 10 seconds.

2023-04-20 11:36:40 ERROR    discord.client Attempting a reconnect in 1.52s
Traceback (most recent call last):
  File "/Users/nicolezhu/mambaforge/envs/gnosisgpt/lib/python3.11/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/Users/nicolezhu/mambaforge/envs/gnosisgpt/lib/python3.11/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
```

**Comment by 0xSage** [comment]
fixed
